routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::resource('posts', 'PostController');
	Route::put('/posts/{id}/restore', 'PostController@restore')->name('posts.restore');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ['user_id', 'title', 'body'];

    public static function boot() {
	    parent::boot();
	    self::saving(function ($post) {
	    	if ( ! \App::runningInConsole()) {
	    		$post->user_id = auth()->id();
		    }
	    });
    }

	public function newQuery() {
		$query = parent::newQuery();
		return $query->withTrashed();
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;

class PostController extends Controller
{
    public function index () {
		$posts = Post::paginate(5);
		return view('posts.index', compact( 'posts'));
    }

    public function show (Post $post) {
	    return view('posts.detail', compact( 'post'));
    }

    public function create () {
    	$titleBtn = "Añadir post";
    	$route = route('posts.store');
    	$method = "POST";
    	$post = new Post;
    	return view('posts.create', compact('titleBtn', 'route', 'method', 'post'));
    }

    public function store () {
    	$this->validate(request(), [
    		'title' => 'required|unique:posts,title|min:10|max:150',
		    'body' => 'required'
	    ]);
    	Post::create(request()->input());
    	return back()->with('message', ['success', 'Post creado correctamente']);
    }

    public function edit ($id) {
	    $titleBtn = "Editar post";
	    $route = route('posts.update', ['id' => $id]);
	    $method = "PUT";
	    $post = Post::findOrFail($id);
	    return view('posts.edit', compact('titleBtn', 'route', 'method', 'post'));
    }

    public function update ($id) {
	    $this->validate(request(), [
		    'title' => 'required|unique:posts,title,'.$id.'|min:10|max:150',
		    'body' => 'required'
	    ]);

	    $post = Post::findOrFail($id);
	    $post->fill(request()->input())->save();
	    return back()->with('message', ['success', 'Post actualizado correctamente']);
    }

    public function destroy ($id) {
    	$post = Post::findOrFail($id);
    	$post->delete();
	    return back()->with('message', ['success', 'Post eliminado correctamente']);
    }

    public function restore ($id) {
		Post::where('id', $id)->restore();
	    return back()->with('message', ['success', 'Post restaurado correctamente']);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">

            @if(session('message'))
                <div class="w-100 p-3">
                    <div class="alert alert-{{ session('message')[0] }}">
                        {{ session('message')[1] }}
                    </div>
                </div>
            @endif

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    @include('posts.partials.form')
@endsection

resources/views/posts/detail.blade.php
@extends('layouts.app')

@section('content')
    @include('posts.partials.post', ['list' => false])
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('posts.partials.form')
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row p-5">

        <div class="col-12 mb-2">
            <a href="{{ route('posts.create') }}" class="btn btn-primary float-right">Añadir post</a>
        </div>

        @forelse ($posts as $post)
            @include('posts.partials.post', ['list' => true])
        @empty
            <div class="w-100 p-3">
                <div class="alert alert-dark text-center">No hay ningún post disponible</div>
            </div>
        @endforelse

        @if ($posts->count())
            {{ $posts->links() }}
        @endif
    </div>
@endsection

resources/views/posts/partials/form.blade.php
<div class="col-12 p-5">
    <div class="col-8 offset-2">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <h2 class="text-center">{{ $titleBtn }}</h2>

        <form method="POST" action="{{ $route }}">
            @csrf

            @method($method)

            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" class="form-control" id="title" name="title" value="{{ old('title') ?: $post->title }}" />
            </div>

            <div class="form-group">
                <label for="body">Body</label>
                <textarea class="form-control" name="body" id="body" rows="3">{{ old('body') ?: $post->body }}</textarea>
            </div>

            <input type="submit" class="btn btn-primary" value="{{ $titleBtn }}" />
            <a class="btn btn-info" href="{{ route('posts.index') }}">Volver al listado</a>
        </form>
    </div>
</div>

resources/views/posts/partials/post.blade.php
<div class="col-12 pb-3">
    <div class="card">
        <div class="card-header">
            ID: {{ $post->id }} - {{ $post->title }}
        </div>
        <div class="card-body">
            {{ $post->body }}
        </div>

        @if ($list)
            <div class="card-footer">
                <div class="float-right">
                    <a href="{{ route('posts.show', ['id' => $post->id]) }}" class="btn btn-info">Detalle</a>
                    <a href="{{ route('posts.edit', ['id' => $post->id]) }}" class="btn btn-secondary">Editar</a>

                    @if($post->trashed())
                        <form method="POST" class="float-right" action="{{ route('posts.restore', ['id' => $post->id]) }}">
                            @csrf
                            @method('PUT')
                            <input type="submit" class="btn btn-default ml-2" value="Restaurar" />
                        </form>
                    @endif

                    <form method="POST" class="float-right" action="{{ route('posts.destroy', ['id' => $post->id]) }}">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger ml-2" value="Eliminar" />
                    </form>
                </div>
            </div>
        @else
            <div class="card-footer">
                <div class="float-right">
                    <a href="{{ route('posts.index') }}" class="btn btn-info">Listado</a>
                </div>
            </div>
        @endif
    </div>
</div>